import requests
import logging
import json
from core.config import settings

logger = logging.getLogger("GrafanaOps")

def create_dashboard_from_sql(title: str, sql_query: str, panel_type: str = "timeseries",
                              description: str = "", dashboard_uid=None) -> dict:
    """
    สร้าง Grafana Dashboard ใหม่ผ่าน API โดยอิงจาก SQL Query ที่ AI คิดมาให้
    panel_type ที่รองรับ: 'timeseries', 'barchart', 'stat', 'table'
    """

    grafana_url = getattr(settings, "GRAFANA_URL", "http://localhost:3000")
    api_key = getattr(settings, "GRAFANA_API_KEY", "")
    datasource_uid = getattr(settings, "GRAFANA_POSTGRES_UID", "")

    if not api_key or not datasource_uid:
        return {"success": False, "error": "Missing GRAFANA_API_KEY or GRAFANA_POSTGRES_UID in config"}

    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json",
        "Accept": "application/json"
    }

    dashboard_payload = {
        "dashboard": {
            "id": None,           # <--- [จุดที่ 1] บังคับให้ Grafana อัปเดตผ่าน UID โดยไม่สน ID ใน DB
            "uid": dashboard_uid,
            "title": title,
            "description": description,
            "tags": ["ai-generated", "hermes"],
            "timezone": "browser",
            "panels": [
                {
                    "title": title,
                    "type": panel_type,
                    "gridPos": {"h": 9, "w": 12, "x": 0, "y": 0},
                    "datasource": {
                        "type": "postgres",
                        "uid": datasource_uid
                    },
                    "targets": [
                        {
                            "datasource": {
                                "type": "postgres",
                                "uid": datasource_uid
                            },
                            "format": "time_series" if panel_type == "timeseries" else "table",
                            "rawQuery": True,
                            "rawSql": sql_query,
                            "refId": "A"
                        }
                    ],
                    "fieldConfig": {
                        "defaults": {
                            "color": {"mode": "palette-classic"},
                            "custom": {
                                "lineWidth": 2,
                                "fillOpacity": 20
                            }
                        }
                    }
                }
            ],
            "schemaVersion": 38
        },
        "overwrite": True,
        "message": "Auto-updated by Olympus-Agents" # (Option) ใส่ note ไว้ใน history ของบอร์ด
    }

    api_endpoint = f"{grafana_url.rstrip('/')}/api/dashboards/db"

    try:
        logger.info(f"📊 Sending request to Grafana to create dashboard: '{title}'")
        response = requests.post(api_endpoint, headers=headers, json=dashboard_payload)

        if response.status_code == 200:
            result = response.json()
            dashboard_url = f"{grafana_url.rstrip('/')}{result.get('url')}"
            returned_uid = result.get('uid') # <--- [จุดที่ 2] ดึง uid ที่ Grafana สร้าง/อัปเดต ให้

            logger.info(f"✅ Dashboard created successfully! URL: {dashboard_url} | UID: {returned_uid}")
            return {
                "success": True,
                "message": f"Dashboard '{title}' saved successfully.",
                "url": dashboard_url,
                "dashboard_uid": returned_uid # <--- ส่งกลับให้ Agent เอาไปจำไว้ใน Context
            }
        else:
            logger.error(f"❌ Grafana API Error: {response.status_code} - {response.text}")
            return {"success": False, "error": response.text}

    except Exception as e:
        logger.error(f"❌ Exception in create_dashboard: {e}")
        return {"success": False, "error": str(e)}


# --- สำหรับเทสระบบ ---
if __name__ == "__main__":
    # 1. จำลองการทำงานครั้งแรก (สร้าง Dashboard ใหม่)
    print("--- 🚀 First Run (Create) ---")
    test_sql_1 = "SELECT issue_key, story_point FROM jira_knowledge WHERE story_point IS NOT NULL;"
    res_create = create_dashboard_from_sql(
        title="[Test] Story Points per Ticket",
        sql_query=test_sql_1,
        panel_type="barchart",
        description="Generated by Olympus Testing (Run 1)"
    )
    print(res_create)

    # 2. จำลองการทำงานครั้งที่สอง (AI ขออัปเดตกราฟเดิม)
    if res_create.get("success"):
        # ดึง UID ที่เพิ่งสร้างสำเร็จออกมา
        saved_uid = res_create.get("dashboard_uid")
        print(f"\n--- 🔄 Second Run (Update Dashboard UID: {saved_uid}) ---")

        # สมมติว่า AI เปลี่ยน Query และเปลี่ยนชื่อกราฟนิดหน่อย
        test_sql_2 = "SELECT issue_key, story_point FROM jira_knowledge WHERE story_point > 3;"
        res_update = create_dashboard_from_sql(
            title="[Test] Story Points per Ticket (Updated)",
            sql_query=test_sql_2,
            panel_type="timeseries",
            description="Updated by Olympus Testing (Run 2)",
            dashboard_uid=saved_uid  # <--- โยน UID กลับเข้าไปเพื่อให้ Grafana รู้ว่าต้องทับบอร์ดไหน
        )
        print(res_update)